### ISSUE TITLE
404 for split files in non-root directory

### ISSUE THREAD

**Issue by am17torres** [polvo/polvo#28]
If i specify an nested folder such as public/js for my output folder the generated public/js/app.js is using absolute paths to the server root.

polvo.yml

```
server:
  root: ./public
  port: 3000

input:
  - ./src

alias:
  app: ./src/app

output:
  js: ./public/js/app.js
  css: ./public/app.css

boot: ./src/app/app
```

public/js/app.js

```
// POLVO :: INITIALIZER
;(function( srcs, done ) {
  var i, loaded = 0, total = srcs.length;
  for( i=0; i<total; i++) {
    var s = document.createElement("script");
    s.type = "text/javascript";
    s.src = srcs[i];

    // ie
    if(window.attachEvent && document.all)
    {
      s.onreadystatechange = function () {
        if(this.readyState === "complete")
          if( ++loaded == total) {
            done()
          }
      };
    }

    // others
    else
    {
      s.onload = function(){
        if( ++loaded == total) {
          done();
        }
      }
    }

    document.getElementsByTagName("head")[0].appendChild(s);
  }
})(["/__split__/app/app.js","/__split__/app/myclass.js","/__split__/templates/main.js"], function(){
  require('src/app/app');
});})()
```

I think we just need to prepend any path segments to each element in the srcs array. I started looking at implementing it myself but I figured you could get it done faster.

Also, I'm not sure how to get a hold of anyone with regards to some other questions I had using this library. It seems very useful, however the lack of information to be found on this library have made it difficult to adopt.
