### ISSUE TITLE
Command line "-s" isn't work ing.

### ISSUE THREAD

**Issue by Wolftein** [polvo/polvo#37]
When i execute "polvo -s"  the server never starts. netstat -n shows me no socket listening on the port i specified in polvo.yml. I'm currently using WIndows 7

**Comment by arboleya** [comment]
Hi @Wolftein, actually the `-s` option works only with the `-w` or `-c`.

`polvo -cs` - compile files + start server
`polvo -ws` - watch/compile files + start server

I'll see if it worths implementing the `-s` to work alone, otherwise just update the docs.

Thanks

**Comment by Wolftein** [comment]
Hi @arboleya, even if do polvo -cw, nothing happends.

i only got "info app doesn't have a `package.json` file, loading built-in plugins only".

I'm using node 0.10.25, and my polvo.yml is

```
server:
  port: 8080
  root: ./public

input:
  - src

output:
  js: ./public/app.js
  css: ./public/app.css

alias:
  helium: ./vendors/helium/src
  app: ./src/app

minify:
  js: false
  css: false

boot: ./src/app/com/game/entry
```
